# Permission for editing module data
# Allowed: Non-operators can import this module, and it's imported by default
# Operator: Operators can import this module using command flags
moduleEditable = {}

# Permission for editing module data
# These values are read-only - changing them here has no effect.
# Always_Allowed: Non-operators can import this module
# Never: This module cannot be imported
[moduleEditableReadOnly]
	"switchy_proxy:proxies" = "ALWAYS_ALLOWED"
