[[curiosSettings]]
  identifier = "curio"
  size = 0
  override = true

[[curiosSettings]]
  identifier = "head"
  size = 1
  override = true

[[curiosSettings]]
  identifier = "necklace"
  size = 1
  override = true

  [[curiosSettings]]
  identifier = "back"
  size = 1
  override = true

  [[curiosSettings]]
  identifier = "bangle"
  size = 0
  override = true

  [[curiosSettings]]
  identifier = "body"
  size = 1
  override = true

  [[curiosSettings]]
  identifier = "bundle"
  size = 1
  override = true

  [[curiosSettings]]
  identifier = "hands"
  size = 2
  override = true

  [[curiosSettings]]
  identifier = "ring"
  size = 3
  override = true

    [[curiosSettings]]
  identifier = "belt"
  size = 1
  override = true

    [[curiosSettings]]
  identifier = "charm"
  size = 3
  override = true
  
    [[curiosSettings]]
  identifier = "feet"
  size = 1
  override = true
