
[Curses]
	#How much damage the player does as a percent.
	#Range: 0 ~ 100
	"Player Damage Dealt" = 50
	#How much damage the player takes as a percent.
	#Range: > 100
	"Player Damage Taken" = 200
	#How much knockback the player takes as a percent.
	#Range: > 100
	"Player Knockback Taken" = 200
	#Should fire last forever on the player until doused manually?
	"Player Burns" = true
	#Should neutral mobs be hostile to the player?
	"Player Angry Neutrals" = true
	#Should the player be unable go to sleep?
	"Player Insomnia" = false

[Benefits]
	#How much experience the player gains from slain mobs as a percent
	#Range: > 100
	"Player Experience" = 300
	#Should the player get unique drops from slain mobs?
	"Player Unique Drops" = true
	#Should the player have an unique fortune level for specific blocks?
	"Player Unique Fortune" = true
	#Should the player have an unique looting level?
	"Player Unique Looting" = true

