
["General Booleans"]
	#Should player paths render?
	v_pathPlayers = true
	#Should mob paths render? This can lag your world
	v_pathMobs = false
	#Should paths be more than dirt and thus permanent
	v_fullPaths = false

["Player Paths"]
	#Upper bound for the randomizer default: 1000.0D
	#Range: 0.0 ~ 2.147483647E9
	v_player_upperLimit = 1000.0
	#The lower bound for the randomizer default: 1.0D
	#Range: 0.0 ~ 2.147483647E9
	v_player_lowerLimit = 1.0

["Chance versus the Player's upper and lower bounds that the following happens"]
	#grass becomes dirt default: 50.0D
	#Range: 0.0 ~ 2.147483647E9
	v_player_grass2dirt = 50.0
	#dirt becomes grass path default: 10.0D
	#Range: 0.0 ~ 2.147483647E9
	v_player_dirt2path = 10.0
	#grass path becomes gravel default: 1.0D
	#Range: 0.0 ~ 2.147483647E9
	v_player_path2gravel = 1.0
	#gravel becomes stone default: 10.0D
	#Range: 0.0 ~ 2.147483647E9
	v_player_gravel2stone = 10.0
	#stone becomes stone bricks default: 10.0D
	#Range: 0.0 ~ 2.147483647E9
	v_player_stone2stonebricks = 10.0

["Mob Paths"]
	#Upper bound for the randomizer default: 1000.0D
	#Range: 0.0 ~ 2.147483647E9
	v_mob_upperLimit = 1000.0
	#The lower bound for the randomizer default: 1.0D
	#Range: 0.0 ~ 2.147483647E9
	v_mob_lowerLimit = 1.0

["Chance versus the Mob's upper and lower bounds that the following happens"]
	#grass becomes dirt default: 50.0D
	#Range: 0.0 ~ 2.147483647E9
	v_mob_grass2dirt = 50.0
	#dirt becomes grass path default: 10.0D
	#Range: 0.0 ~ 2.147483647E9
	v_mob_dirt2path = 10.0
	#grass path becomes gravel default: 1.0D
	#Range: 0.0 ~ 2.147483647E9
	v_mob_path2gravel = 1.0
	#gravel becomes stone default: 10.0D
	#Range: 0.0 ~ 2.147483647E9
	v_mob_gravel2stone = 10.0
	#stone becomes stone bricks default: 10.0D
	#Range: 0.0 ~ 2.147483647E9
	v_mob_stone2stonebricks = 10.0

