
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.diet]
		enable_compat_diet = true
		#Disable diet functionality for vampires
		disableVampireDiet = true

