#Maximum Y value for arcanum ore veins
#Range: 1 ~ 10
arcanumOreMaxY = 4

#Graphics settings
[graphics]
	#Enable better particle/effect layering.
	#Fixes particles and effects rendering behind clouds and weather.
	#NOTE: Does NOT work with fabulous graphics mode.
	betterLayering = true
	#Enable large item models.
	largeItemModel = true

